services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./data/:/root/
    networks: [ollama]

  maker-server:
    build: ./server
    container_name: maker-server
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - OLLAMA_PORT=${OLLAMA_PORT}
    volumes:
      - ./config/maker:/app/config
      - ./data/maker/specifications:/app/specifications
    networks:
      traefik:
      ollama:
        ipv4_address: 172.11.0.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maker-http.rule=Host(`maker.app.io`) ||
        Host(`maker`)"
      - "traefik.http.routers.maker-http.entrypoints=web"
      - "traefik.http.routers.maker-http.service=maker-service"
      - "traefik.http.services.maker-service.loadbalancer.server.port=8000"

      - "traefik.http.routers.maker-public-http.rule=Host(`maker.bidn.dev`)"
      - "traefik.http.routers.maker-public-http.entrypoints=web"
      - "traefik.http.routers.maker-public-http.service=maker-service-public"
      - "traefik.http.services.maker-service-public.loadbalancer.server.scheme=\
        http"
      - "traefik.http.services.maker-service-public.loadbalancer.server.port=80\
        00"
    depends_on: [ollama]

networks:
  ollama:
    name: ollama
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/24
          gateway: 172.11.0.1
  traefik:
    external: true
